### PR TITLE
Dependency bump to address Dependabot security vulnerabilities

### PR DESCRIPTION
**Pull request by KaelanNeoFinancial**
Updated all packages to latest version, except for Globby and Strip-ANSI due to Jest compatibility.

### CODE REVIEW

**Comment by Senney** [comment]
Seems like there's a problem causing the built copy of ccscan to fail to run. I'll do some digging to see why it's failing!

**Comment by usernameseb** [comment]
What's the status of this PR?

**Review by usernameseb — COMMENTED** [review]
@KaelanNeoFinancial what's the status of this PR? Were you able to address Ian's comments?

**Comment by KaelanNeoFinancial** [comment]
@usernameseb not sure. I replaced Yarn with npm, but tests were failing to run locally. I had the same problem with Yarn though, so not sure. Want to chat about this when you have some free-er time?

**Pull request closed without merging**
